build:
	ocamlbuild -use-ocamlfind -pkg graphics -pkg unix CPbattleship.ml CPbattleship.d.byte
test:
	ocamlbuild -use-ocamlfind -pkg graphics -pkg unix CPbattleship_test.ml CPbattleship_test.d.byte
clean:
	ocamlbuild -clean